language: python
sudo: false

python:
    - '2.7'
    - '3.6'

install:
    - pip install -U pip setuptools flake8

script:
    - flake8 .
    - python setup.py test

# deploy:
#   provider: pypi
#   on:
#     tags: true
